### PR TITLE
update spec to 0.14.5

### PR DESCRIPTION
**Pull request by bnied**

### CODE REVIEW

**Comment by kc1212** [comment]
Hi @bnied, sorry I don't plan to maintain this spec file anymore. I started using [Nix](https://nixos.org/nix/) in Fedora (or any other distro). The Syncthing package there is follows the official release pretty closely.

**Comment by bnied** [comment]
@kc1212 that's cool. Mind if I maintain it in your stead?

**Comment by kc1212** [comment]
@bnied certainly, would you like to have the ownership or you'll just fork it?

**Comment by bnied** [comment]
I've forked the repo, so I can continue maintaining it there. :)

**Pull request merged**
